//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test14
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Товары в наличии.
    /// </summary>
    // *** Start programmer edit section *** (ВНаличии CustomAttributes)

    // *** End programmer edit section *** (ВНаличии CustomAttributes)
    [AutoAltered()]
    [Caption("Товары в наличии")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВНаличииE", new string[] {
            "Количество as \'Количество\'",
            "Дата as \'Дата\'"})]
    [View("ВНаличииL", new string[] {
            "Количество as \'Количество\'",
            "Дата as \'Дата\'"})]
    public class ВНаличии : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private System.DateTime fДата;
        
        // *** Start programmer edit section *** (ВНаличии CustomMembers)

        // *** End programmer edit section *** (ВНаличии CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ВНаличии.Дата CustomAttributes)

        // *** End programmer edit section *** (ВНаличии.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ВНаличии.Дата Get start)

                // *** End programmer edit section *** (ВНаличии.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ВНаличии.Дата Get end)

                // *** End programmer edit section *** (ВНаличии.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВНаличии.Дата Set start)

                // *** End programmer edit section *** (ВНаличии.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ВНаличии.Дата Set end)

                // *** End programmer edit section *** (ВНаличии.Дата Set end)
            }
        }
        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (ВНаличии.Количество CustomAttributes)

        // *** End programmer edit section *** (ВНаличии.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (ВНаличии.Количество Get start)

                // *** End programmer edit section *** (ВНаличии.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (ВНаличии.Количество Get end)

                // *** End programmer edit section *** (ВНаличии.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВНаличии.Количество Set start)

                // *** End programmer edit section *** (ВНаличии.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (ВНаличии.Количество Set end)

                // *** End programmer edit section *** (ВНаличии.Количество Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВНаличииE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВНаличииE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВНаличииE", typeof(IIS.Test14.ВНаличии));
                }
            }
            
            /// <summary>
            /// "ВНаличииL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВНаличииL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВНаличииL", typeof(IIS.Test14.ВНаличии));
                }
            }
        }
    }
}
